//! Build-time route discovery — scans `resources/routes/` like TanStack
//! Router and emits a `ROUTES` table that the binary `include!`s.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let routes_dir = Path::new(&manifest_dir).join("../resources/routes");
    let routes_dir = match routes_dir.canonicalize() {
        Ok(p) => p,
        Err(_) => {
            eprintln!("cargo:warning=resources/routes/ not found — generating empty router");
            write_empty(&manifest_dir);
            return;
        }
    };

    println!("cargo:rerun-if-changed={}", routes_dir.display());

    let mut routes = vec![];
    visit(&routes_dir, "", &mut routes);
    // Most-specific first: more segments win; among equal, fewer `:` params
    // beat more `:` params (i.e. literal `/users/create` ranks above
    // `/users/:id`).
    routes.sort_by_key(|r| {
        let segs = r.url.matches('/').count();
        let params = r.url.matches(":").count();
        (std::cmp::Reverse(segs), params)
    });

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs from resources/routes/\n");
    for (i, r) in routes.iter().enumerate() {
        code.push_str(&format!(
            "#[path = \"{}\"]\nmod r{};\n",
            r.file_path.display().to_string().replace('\\', "/"),
            i
        ));
    }
    code.push_str(
        "\npub fn routes() -> &'static [::tars_frontend::Route] {\n    &[\n",
    );
    for (i, r) in routes.iter().enumerate() {
        code.push_str(&format!(
            "        ::tars_frontend::Route {{ path: \"{}\", component: r{}::component }},\n",
            r.url, i
        ));
    }
    code.push_str("    ]\n}\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("generated_routes.rs");
    fs::write(dest, code).unwrap();
}

struct Discovered {
    url: String,
    file_path: PathBuf,
}

fn visit(dir: &Path, prefix: &str, out: &mut Vec<Discovered>) {
    let read = match fs::read_dir(dir) {
        Ok(r) => r,
        Err(_) => return,
    };
    for entry in read.flatten() {
        let path = entry.path();
        if path.is_dir() {
            let segment = path.file_name().unwrap().to_string_lossy().to_string();
            let new_prefix = format!("{}/{}", prefix, segment_to_url(&segment));
            visit(&path, &new_prefix, out);
        } else if path.extension().map(|s| s == "rs").unwrap_or(false) {
            let stem = path.file_stem().unwrap().to_string_lossy().to_string();
            let url = if stem == "index" {
                if prefix.is_empty() { "/".into() } else { prefix.to_string() }
            } else {
                format!("{}/{}", prefix, segment_to_url(&stem))
            };
            out.push(Discovered { url, file_path: path });
        }
    }
}

/// Translate a filename segment to a URL segment. `[id]` → `:id` so the
/// router treats it as a parameter.
fn segment_to_url(seg: &str) -> String {
    if let Some(inner) = seg.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
        format!(":{}", inner)
    } else {
        seg.to_string()
    }
}

fn write_empty(manifest_dir: &str) {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("generated_routes.rs");
    fs::write(
        dest,
        "pub fn routes() -> &'static [::tars_frontend::Route] { &[] }\n",
    )
    .unwrap();
    let _ = manifest_dir;
}
